export const NEW_STEP = 'NEW_STEP';
export const ADD_CNPJ_INFO = 'ADD_CNPJ_INFO';
export const ADD_BUSINESS_INFO = 'ADD_BUSINESS_INFO';
export const ADD_ADDRESS_INFO = 'ADD_ADDRESS_INFO';
export const ADD_BUSINESS_STORE_INFO = 'ADD_BUSINESS_STORE_INFO';
export const ADD_LOGO_INFO = 'ADD_LOGO_INFO';
